- name: copy {{ component }} service file to /etc/systemd/system/{{ component }}.service
  ansible.builtin.copy:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: reload the {{ component }} service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: "{{ component }}" # --------->

- name: start and enable the {{ component }} service
  ansible.builtin.service:
    name: {{ component }}
    state: started
    enabled: yes